templates: 
  test:
    add:
      project: Test
      tags:
        - work
        - someday
      priority: L
    report:
      filters:
        project: Test
        tags:
          - test
      report: test
config:
  editor: "vim"
  notes:
    path: "/path/to/notes"
